export const BRANCH_FETCH_REQUEST = 'BRANCH_FETCH_REQUEST'
export const BRANCH_FETCH_SUCCESS = 'BRANCH_FETCH_SUCCESS'
export const BRANCH_FETCH_FAIL = 'BRANCH_FETCH_FAIL'
export const BRANCH_FETCH_RESET = 'BRANCH_FETCH_RESET'

export const BRANCH_ADD_REQUEST = 'BRANCH_ADD_REQUEST'
export const BRANCH_ADD_SUCCESS = 'BRANCH_ADD_SUCCESS'
export const BRANCH_ADD_FAIL = 'BRANCH_ADD_FAIL'
export const BRANCH_ADD_RESET = 'BRANCH_ADD_RESET'
